# Generated by Django 4.1.4 on 2023-05-16 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_job_id_alter_job_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.part_number'),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
