# Generated by Django 4.1.4 on 2023-05-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_job_id_job_part_number_alter_job_job_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
