# Generated by Django 4.1.4 on 2023-05-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_job_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='tsn',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tso',
        ),
        migrations.AddField(
            model_name='part_number',
            name='tsn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='part_number',
            name='tso',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
