# Generated by Django 4.1.4 on 2023-05-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_job_tsn_remove_job_tso_part_number_tsn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartNumberChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, max_length=300, null=True)),
                ('tsn', models.CharField(blank=True, max_length=100, null=True)),
                ('tso', models.CharField(blank=True, max_length=100, null=True)),
                ('part_namber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.part_number')),
            ],
        ),
    ]
