# Generated by Django 4.1.4 on 2023-05-16 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_partnumberchild'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartFullForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tsn', models.CharField(blank=True, max_length=100, null=True)),
                ('tso', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TSO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='part_number',
        ),
        migrations.RemoveField(
            model_name='part_number',
            name='tsn',
        ),
        migrations.RemoveField(
            model_name='part_number',
            name='tso',
        ),
        migrations.DeleteModel(
            name='PartNumberChild',
        ),
        migrations.AddField(
            model_name='partfullform',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.job'),
        ),
        migrations.AddField(
            model_name='partfullform',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.part_number'),
        ),
    ]
