# Generated by Django 4.1.4 on 2023-05-16 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_partfullform_tsn_tso_remove_job_part_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PO',
        ),
        migrations.DeleteModel(
            name='TSN',
        ),
        migrations.DeleteModel(
            name='TSO',
        ),
        migrations.RemoveField(
            model_name='job',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='job',
            name='po_image',
            field=models.ImageField(blank=True, null=True, upload_to='po_images'),
        ),
        migrations.AddField(
            model_name='job',
            name='po_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='partfullform',
            name='description',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='partfullform',
            name='part_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.part_number'),
            preserve_default=False,
        ),
    ]
