# Generated by Django 4.1.4 on 2023-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_po_delete_tsn_delete_tso_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Part_Number',
            new_name='PartNumber',
        ),
        migrations.AddField(
            model_name='job',
            name='part_numbers',
            field=models.ManyToManyField(blank=True, through='myapp.PartFullForm', to='myapp.partnumber'),
        ),
    ]
