# Generated by Django 4.2.1 on 2023-05-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_rename_part_number_partnumber_job_part_numbers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='part_numbers',
        ),
    ]
